device: cuda

runtime:
  default:
    llama_host: http://ml-004.eluvio:11434
    llama_model: llama3.3:70b
    prompt: Translate the following French text to English, please maintain the timestamps from the input.

postprocessing:
  # if words are this far apart, they are not considered for being in the same sentence. (in milliseconds)
  sentence_gap: 5000
